### ISSUE TITLE
Error file MUA3 .g1n

### ISSUE THREAD

**Issue by Digote** [lehieugch68/G1N-Font-Editor#1]
First, congratulations on the tool. I haven't found anything related to .g1n files from Koei Tecmo here on GitHub yet. I'll leave here a file from the game Marvel Ultimate Alliance 3. I'm trying to localize it; I've managed to handle the text part, but I'm stuck on this font file, which is missing some accents. I've tried altering some things in Xadvanced, but I haven't had success yet.

**File**
[ENG_font.zip](https://github.com/lehieugch68/G1N-Font-Editor/files/14859480/ENG_font.zip)

**Error**
![Captura de tela 2024-04-03 201636](https://github.com/lehieugch68/G1N-Font-Editor/assets/45742711/d6b92f9d-7ae3-49e7-bc65-220dd99ebd16)

**Comment by lehieugch68** [comment]
Thanks for reporting the bug. It has been resolve in the [latest version](https://github.com/lehieugch68/G1N-Font-Editor/releases/tag/1.0.0.2).
