### ISSUE TITLE
Problems editing the font of the Fate/Samurai Remnant game

### ISSUE THREAD

**Issue by Digote** [lehieugch68/G1N-Font-Editor#3]
After a long time, I finally managed to find the font files for the game Fate/Samurai Remnant.

With your tool, I will be able to translate them into my language. Thank you very much; it's an excellent tool.

The only problem that's happening is that after I open and save it, the font looks like this without making any changes. This font has 3 pages.

The game itself has 5 fonts, but this smaller one that I'm going to send you seems to be the English one. The same thing happens when I try to change other languages.

Once again, thank you for your help.

--------------------------------------------------------------------------------------------------------------

**Original .g1n**

[fddb949b9251ecfd.zip](https://github.com/user-attachments/files/16036525/fddb949b9251ecfd.zip)

**.g1n modified**
[fddb949b9251ecfd.zip](https://github.com/user-attachments/files/16036532/fddb949b9251ecfd.zip)

------------------------------------------------------------------------------------------------------------------

**Video**

https://github.com/lehieugch68/G1N-Font-Editor/assets/45742711/6c973ec9-8a4c-4c36-b4a0-ad3bead6fdfb

**Comment by lehieugch68** [comment]
Thanks for reporting the issue. Please try the new version to see if it has been resolved.

**Comment by Digote** [comment]
Perfect, I managed to test it, now I'm going to adjust the font.

Thank you again.


![fate](https://github.com/lehieugch68/G1N-Font-Editor/assets/45742711/e0088187-f247-4838-9a86-9a31c747e32c)
